services:
  - type: web
    name: employee-management-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 16
    autoDeploy: true 