services:
  # Backend API service
  - type: web
    name: employee-management-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 16
    autoDeploy: true

  # Frontend Angular service
  - type: web
    name: employee-management-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist/frontend
    envVars:
      - key: NODE_VERSION
        value: 16
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 